root = "."
testdata_dir = "testdata"
tmp_dir = "build"

[build]
  args_bin = []
  bin = "./build/app"
  cmd = "go build -gcflags='all=-N -l' -o ./build/app main.go"
  delay = 0
  exclude_dir = ["assets", "build", "vendor", "testdata", "temp"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = false
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "env"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  rerun = true
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[log]
  main_only = true
  time = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true
  keep_scroll = false