# .air.toml
[build]
  bin = "tmp/main"  # Output binary path
  cmd = "./shortlink"  # Command to run your app
  include = ["*.go"]  # Watch for changes in .go files
  exclude = []  # Exclude no files

[log]
  time = true  # Print time with logs
  level = "info"  # Log level
