project_path = "./ShortLink"

[phases.setup]
# Use Node.js as the environment for the project
runtime = "nodejs"

[phases.install]
# Install dependencies using npm or yarn (modify based on your setup)
cmds = ["npm install --omit=dev"]

[phases.build]
# Build the Vite project
cmds = ["npm run build"]

[phases.start]
# Serve the static files using a simple HTTP server (or Railway's built-in static hosting)
cmds = ["npx serve -s dist"]