[build]
# Use `npm ci --omit=dev` to install production dependencies only, then build using Vite
command = "npm ci --omit=dev && npm run build"

[start]
# Start the app using Vite's preview mode (serve the production build)
command = "npm run preview"
